= Processing  SQL statements with JDBC(Java DataBase Connect)

* It has the following steps to follow :
1. Establishing a database connection
2. Creating a statement
3. Execute the query to perform the database operation and fetch the ResultSet in some cases
4. Process the obtained ResultSet Object
5. Closing the Connections,Statement and ResultSet.

== Establishing a Connection

* In order to perform any database operation we firsly need to establish a connection with database for that we can either use the database containers or locally download the database or use the databases that can be accessed by using some Urls.
* Here in JDBC we use the term DataSource which refers to the database/DBMS or a legacy filesystem with the corresponding JDBC driver.
* We have two classes in order to establish connection with the database :
** DriverManager : This is a fully implemented class that connects the application to the datasource using the database url
** DataSource : This interface is provided over the DriverManager since it allows details of the underlying datasource to be transparent to the application
* For now we are using the DriverManager for establishing the connection and the Datasource class also use almost process and method to establish the connection.

* In order to connect to the datasource using the driver manager we need to provide the database url, username and password to the [red]#DriverManager# class [yellow]#getConnection()# method and it returns the Connection Object.

** Example for a jdbc url is : jdbc:mysql://localhost:3306/userdb --  where userdb is the database name located on the server.

== Creating Statements

* Once a connection is established then we need to prepare the statements ,the statements are the objects that deal with the database queries,these carry the SQL statement/query in the form a string.Simply,A Statement is an interface that represents a SQL statement.
* There are three types of Statements :
** Statement : Used to implement the simple SQL statements with no parameters.
** PreparedStatement : This class extends the Statement which is used for precompiling the SQL statements that might contain input parameters.
** CallableStatement : This class extends the PreparedStatement class and is used to execute the stored Procedures that may contain both input and output parameters

* A PreparedStatenent object is more convinient to use that a simple Statement.If it is for simple SQL statement that is used only one or twice we can go for Statement Object but incase we need to use the Statement so many times then we need to go for PreparedStatement since it reduces the compilation time and increases the speed for quering database.The reason is:
** A simple Statement simply creates an SQL statenent from the string and then provide it to the datasource,the datasource then compile the statement and run it where as when using the PreparedStatement the preparedStatement object creates the SQL statement and compile the statement before providing it to the database,the database simply need to run the compiled statement and return the outcome.
** Another reason for using the prepareStatement over Statement object is that the prepareStatement provides extra support of accepting the input parameters where the Statement is used for only executing the general or simple statement.
** PreparedStatement provides the protection from SQL Injection which is one of the method for hacking

*Creating a preparedStatement :*

----
String query = "SELECT LASTNAME,COUNTRY FROM EMPLOYEES WHERE ID = ? AND FIRSTNAME = ?"; <1>

PreparedStatement psmt = con.preparedStatement(query); <2>

psmt.setInt(1,10); <3>
psmt.setString(2,"SUDHEER"); <4>
ResultSet/int/boolean result = psmt.executQuery/executeUpdate/execute; <5>
----

1. Create a string which will become an sql statement by feeding it to the statement object.
2. A preparedStatement object being made by passing the string as parameter.
3. 3&4 represents feeding the parameters with values ,here *?* represents a placeholder,1 represents the first parameter and 2 represents the second parameter.The PreparedStatement will only have set methods like setInt,setFloat,setString etc.
** Once after the setting the parameters and executing the query the parameters are not cleared until we the method clearParameters on the statement object but these can be overridden with different values.

----
From the above example only
1.After the execute statement the parameters are not erased so if we want to do one more update where we want only to change the second param and leave the first param as it is we just need to override/update the second param only.
psmt.set(2,"Mounika");
psmt.execute(); --> this will set the parameters to be 1 as 10 and 2 as Mounika.
----

== Executing the PreparedStatement objects

* Once a statement has been prepared and all the parameter are set we need to execute the queries.For executing the queries we have 3 different methods and these are used based on the scenarios:
** execute : This method returns [red]*true* if the first object that the query returns is a ResultSet Object.This method is used when the query return one or more that one ResultSet object.To retrive the ResultSet objects repeatedly call Statement.getResultSet().
** executeQuery : This method returns a ResultSet Object.This accepts a query in the form a string
** executeUpdate : This methods returns an int value represnting the number of rows affected by the SQL statement.This method is used for using INSERT,DELETE,UPDATE SQL statements.No agruments are supplied to the executeUpdate method.

== Using Transactions

* There might arise some situations where we want one statement to take effect unless another one completes or may be we need to update one or more statements all at once otherwise data integrity might be lost.
* When a connection is established then the connection will be in auto-commit mode that means each individual SQL statement is treated as a transaction and is automatically committed right after it is executed but when we want more than one statement to be executed at once that is one or more statement under a single transaction then we need to disable the auto commit mode. using con.setAutoCommit(false).
* Once after executing all the statements then commit using con.commit() which will commit all the statements under a single transction.
* Before commit if one want to rollback any change he/she made he can use the save points at different points and use those save points to roll back which will rollback the current state to the saved state.

== Processing ResultSet Object

* A ResultSet object is a table of data representing a database result set which is usually generated by executing a statement that queries the database
* We can access the data in a resultset object using a cursor which is not a database cursor but a pointer that points to one row of data in the ResultSet.When a ResultSet object is returned the cursor is positioned before the first row,in order to move the cursor to the next row use the method resultSet.next() ,this method returns true or false.
=== ResultSet Interface
* A ResultSet interface provides methods for retrieving and manipulating the results of executed queries.The Characterstics of ResultSet are type,concurrency and cursor holdability.

1. Types :
The type determines the level of its functionality in two areas :
** The way in which the cursor can be manipulated i.e to move forward or backward
** How the concurrent changes made to the underlying data source are reflected by the ResultSet object.

=== Types :

** *TYPE_FORWARD_ONLY* : The result set cursoe can only move forward from before first row to after last row, it contains the rows that satisfy the query at the time of execution of the query or as the rows are retrieved.
** *TYPE_SCROLL_INSENSITIVE* : The result set cursor can move either in forward direction or in the backward direction relative to the current position and it can move to an absolute positiion and it contains the rows that satisfy the query at the time of execution of the query or as the rows are retrieved.
** *TYPE_SCROLL_SENSITIVE* : THe result set cursor can move both forward and backward relative to the current position and it can move to an absolute position.The result set reflects changes made to the underlying datasource while the result set remains open.

NOTE: The default ResultSet type is TYPE_FORWARD_ONLY.

=== ResultSet Concurrency

This property determines what level of update functionality is supported.
* It has two levels :
** CONCUR_READ_ONLY : The resultSet object cannot be updated using the resultset interface.
** CONCUR_UPDATABLE : The ResultSet object can be updated using the resultset interface.

NOTE: The default ResultSet concurrency is CONCUR_READ_ONLY.

=== Cursor Holdability

* When a commit method is called it will close the ResultSet object(cursor),this property gives the application control over whether ResultSet objects(cursors) can be closed when commit is called.
* Types :
** HOLD_CURSORS_OVER_COMMIT: ResultSet cursors are not closed; they are holdable: they are held open when the method commit is called.
Holdable cursors might be ideal if your application uses mostly read-only ResultSet objects.
** CLOSE_CURSORS_AT_COMMIT: ResultSet objects (cursors) are closed when the commit method is called.
Closing cursors when this method is called can result in better performance for some applications.

NOTE: Default value for this property depends on DBMS.

== Retrieving Column values for Rows

* The ResultSet interface declares getter methods for retrieving column values from the current row.
The values can be retrieved using either the index number of the column or the alias or name of the column.
* The column indez is usually more efficient.The columns are numbered from 1 and the indezing starts from left to right
* There are many methods like getInt(),getFloat,getString() etc but the getString() method can be used for retrieving all the column values where the retrieved value will be a string and then we need to get the original value from the string value

=== Cursors

* The data in the resultSet is accessed using the cursor.However, when a ResultSet object is first created, the cursor is positioned before the first row.There are other methods available to move the cursor :
** next: Moves the cursor forward one row.
Returns true if the cursor is now positioned on a row and false if the cursor is positioned after the last row.
** previous: Moves the cursor backward one row.
Returns true if the cursor is now positioned on a row and false if the cursor is positioned before the first row.
** first: Moves the cursor to the first row in the ResultSet object.
Returns true if the cursor is now positioned on the first row and false if the ResultSet object does not contain any rows.
** last: Moves the cursor to the last row in the ResultSet object.
Returns true if the cursor is now positioned on the last row and false if the ResultSet object does not contain any rows.
** beforeFirst: Positions the cursor at the start of the ResultSet object, before the first row.
If the ResultSet object does not contain any rows, this method has no effect.
** afterLast: Positions the cursor at the end of the ResultSet object, after the last row.
If the ResultSet object does not contain any rows, this method has no effect.
** relative(int rows): Moves the cursor relative to its current position.
** absolute(int row): Positions the cursor on the row specified by the parameter row.

* Updating Rows in ResultSet object:
** You cannot update a default ResultSet object, and you can only move its cursor forward.
However, you can create ResultSet objects that can be scrolled (the cursor can move backwards or move to an absolute position) and updated.

----
    try (Statement stmt =
      con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
      ResultSet uprs = stmt.executeQuery("SELECT * FROM COFFEES");
      while (uprs.next()) {
        float f = uprs.getFloat("PRICE");
        uprs.updateFloat("PRICE", f * percentage); <1>
        uprs.updateRow(); <2>
      }
    } catch (SQLException e) {
      JDBCTutorialUtilities.printSQLException(e);
    }
----

1. uprs.updatefloat() --  this method only updates only specified column but dont update/commit to the database.
2. uprs.updateRow() --  this method updates the specified row to the database

== Update the statement objects for Batch Upates

* Under this features instead of running each statement individually ,the set of statements are added to the same Statement objects one by one to batch them and batchUpdate all the statements once.

*Code Example*

----
 stmt.addBatch("INSERT INTO COFFEES " +
                    "VALUES('Amaretto', 49, 9.99, 0, 0)");
      stmt.addBatch("INSERT INTO COFFEES " +
                    "VALUES('Hazelnut', 49, 9.99, 0, 0)");
      stmt.addBatch("INSERT INTO COFFEES " +
                    "VALUES('Amaretto_decaf', 49, 10.99, 0, 0)");
      stmt.addBatch("INSERT INTO COFFEES " +
                    "VALUES('Hazelnut_decaf', 49, 10.99, 0, 0)");

      int[] updateCounts = stmt.executeBatch();
      con.commit();
----

* The method Statement.addBatch adds a command to the list of commands associated with the Statement object stmt.
In this example, these commands are all INSERT INTO statements, each one adding a row consisting of five column values.
The values for the columns COF_NAME and PRICE are the name of the coffee and its price, respectively.
The second value in each row is 49 because that is the identification number for the supplier, Superior Coffee.
The last two values, the entries for the columns SALES and TOTAL, all start out being zero because there have been no sales yet.
* Note that stmt uses the method executeBatch to send the batch of insertions, not the method executeUpdate, which sends only one command and returns a single update count.
The DBMS executes the commands in the order in which they were added to the list of commands

== Inserting Rows in ResultSet Object:

* Create a statement object that should be able to update a resultset object using the CONCUR_UPDATABLE property
* We cannot directly create a row in the database or insert the data column by column,firslty we have to create a buffer that acts as an individual row for the given resultSet,once all the data is filled to the buffered row then we can insert the row to the database.

----
ResultSet uprs = stmt.executeQuery("SELECT * FROM COFFEES");
      uprs.moveToInsertRow();
      uprs.updateString("COF_NAME", coffeeName);
      uprs.updateInt("SUP_ID", supplierID);
      uprs.updateFloat("PRICE", price);
      uprs.updateInt("SALES", sales);
      uprs.updateInt("TOTAL", total);

      uprs.insertRow();
      uprs.beforeFirst();
----

* The resultset is moved to buffer mode by using moveToInsertRow() method,once the buffered row is filled with data move the buffer to the database using insertRow() method

----

Note: After inserting a row with the ResultSet.insertRow, you should move the cursor to a row other than the insert row. For example, this example moves it to before the first row in the result set with the method ResultSet.beforeFirst. Unexpected results can occur if another part of your application uses the same result set and the cursor is still pointing to the insert row.
----

=== Closing the connections
* When you are finished using a Connection, Statement, or ResultSet object, call its close method to immediately release the resources it's using.

NOTE: Alternatively, use a try-with-resources statement to automatically close Connection, Statement, and ResultSet objects, regardless of whether an SQLException has been thrown i.e : try (Statement stmt = con.createStatement()) ,whether there is an exception or not the statement resource will be closed when the try block terminates.All the resources Statement,Connection,ResultSet when used inside the try will be closed when the try terminates.
